name: AKS Deployment

on: 
 workflow_dispatch:
  inputs:
    azure-aks:
        description: 'Solution Name'
        required: true
        type: string
    azure-aks-rg:
        required: true
        type: string
    helm-repo-path:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
    contents: read
    packages: write
    attestations: write
    id-token: write

jobs:   
  deploy:
    uses: CSCorpIt/reusable-workflows/.github/workflows/aks_deploy.yml@main
    with:
      azure-aks: ${{inputs.azure-aks}}
      azure-aks-rg: ${{inputs.azure-aks-rg}}
      helm-repo-path: ${{inputs.helm-repo-path}}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_GITHUB_APP }}
      AZURE_SUB_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
